name: Flutter Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. جلب سورس كود المشروع
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. إعداد لغة Java
      - name: Set up Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      # 3. إعداد بيئة Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      # 4. تحميل الحزم والمكتبات
      - name: Install dependencies
        run: flutter pub get

      # 5. بناء ملف APK
      - name: Build APK
        run: flutter build apk --release

      # 6. رفع ملف الـ APK كـ Artifact لتتمكن من تحميله
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
          
